id: I94D9E28A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:10:24+00:00'
last_modified: '2022-06-10T06:38:06.918602+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN487
  title: ཐེག་དགུ་སྤྱི་ཆིངས་ཀྱི་རྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6912':
      image_group_id: I3CN21125
      title: Volume 1 of theg dgu spyi chings kyi rtsa 'grel/
      total_pages: 362
      order: 1
      base_file: 6912.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
